# Generated by Django 2.2.7 on 2019-11-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=60)),
                ('employee_salary', models.IntegerField()),
                ('employee_age', models.IntegerField()),
                ('profile_image', models.ImageField(blank=True, upload_to='img')),
            ],
        ),
    ]
