# Generated by Django 2.2.7 on 2019-11-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_age',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_salary',
            field=models.CharField(max_length=60),
        ),
    ]
