# Generated by Django 2.2.7 on 2019-11-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20191112_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='profile_image',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
